apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:                                                           
    helm.sh/hook-weight: "360"
  name: {{ .Values.cluster.name }} 
  namespace: {{ .Values.cluster.name }} 
  labels:
    cloud: 'AWS'
    region: 'eu-west-1'
    vendor: OpenShift
    hive.openshift.io/cluster-platform: aws
    cluster.open-cluster-management.io/clusterset: 'default'
spec:
  baseDomain: {{ .Values.cluster.baseDomain }}
  clusterName: {{ .Values.cluster.name }}'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    aws:
      credentialsSecretRef:
        name: {{ .Values.cluster.name }}-aws-creds
      region: eu-west-1
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.cluster.name }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.cluster.name }}-ssh-private-key
    imageSetRef:
      name: img{{ .Values.imageName }}-multi-appsub
  pullSecretRef:
    name: {{ .Values.cluster.name }}-pull-secret
