apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  annotations:
    helm.sh/hook-weight: "360"
  name: {{ .Values.cluster.name }}-worker
  namespace: {{ .Values.cluster.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
      zones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
  replicas: {{ .Values.workers.count }} 
