apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-install-config
  namespace: {{.Values.cluster.name }}
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: '{{ .Values.cluster.name }}'
    baseDomain: {{ .Values.cluster.baseDomain }}
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: {{ .Values.masters.count }}
      platform:
        aws:
          zones:
          - eu-west-1a
          - eu-west-1b
          - eu-west-1c
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: {{ .Values.workers.count }}
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
          zones:
          - eu-west-1a
          - eu-west-1b
          - eu-west-1c
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 172.18.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: eu-west-1
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAJRJuCD7XjKfVCpY3uLI/4uhgeRKpJvmKrgG/8lNZ+2 prajendr@prajendr-mac
