apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
stringData:
  aws_access_key_id: {{ .Values.provider.access }}
  aws_secret_access_key: {{ .Values.provider.secret }}

