apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-pull-secret
  namespace: {{ .Values.cluster.name }}
stringData:
  .dockerconfigjson: 
type: kubernetes.io/dockerconfigjson
